### ISSUE TITLE
Errors when compiling *.ld files

### ISSUE THREAD

**Issue by cierzniak** [thiagoralves/OpenPLC_RaspberryPi-Interface#1]
When I try to put any example ladder file into OpenPLC I've got problem such as:
````bash
OPLC_Compiler exit code: 0
moving files...
compiling OpenPLC...
stdout:
stderr: ./core/ladder.cpp:58:26: error: 'DiscreteInputBuffer1' was not declared in this scope
 STATIC BOOL *U_b_X1_0 = &DiscreteInputBuffer1[0];
                          ^
./core/ladder.cpp:59:26: error: 'CoilsBuffer1' was not declared in this scope
 STATIC BOOL *U_b_Y1_0 = &CoilsBuffer1[0];
                          ^
./core/ladder.cpp:60:26: error: 'DiscreteInputBuffer1' was not declared in this scope
 STATIC BOOL *U_b_X1_1 = &DiscreteInputBuffer1[1];
                          ^

exec error: Error: Command failed: /bin/sh -c g++ -lrt -lwiringPi -lpthread ./core/*.cpp -o ./core/openplc
./core/ladder.cpp:58:26: error: 'DiscreteInputBuffer1' was not declared in this scope
 STATIC BOOL *U_b_X1_0 = &DiscreteInputBuffer1[0];
                          ^
./core/ladder.cpp:59:26: error: 'CoilsBuffer1' was not declared in this scope
 STATIC BOOL *U_b_Y1_0 = &CoilsBuffer1[0];
                          ^
./core/ladder.cpp:60:26: error: 'DiscreteInputBuffer1' was not declared in this scope
 STATIC BOOL *U_b_X1_1 = &DiscreteInputBuffer1[1];
                          ^

error compiling OpenPLC. Please check your ladder diagram
````

Ladder example file:
![ladder](https://cloud.githubusercontent.com/assets/815618/12327912/3a2efe04-bad9-11e5-9a43-94938a5938a9.PNG)

Raspberry Pi B 512MB RAM with Raspbian Jessie
Installed WiringPI from git master branch and NodeJS v5.4.1 armv6l

**Comment by thiagoralves** [comment]
I couldn't see the image for your Ladder (it appeared as a broken link on
my email), but for the errors I saw on the OpenPLC log, it seems that
you're using contacts X1_0 and X1_1 and coil Y1_0 on your program.

Only buffer0 is declared for the RaspberryPi. Therefore, use variable names
X0_0 through X0_6 for contacts and Y0_0 through Y0_4 for coils in your
Ladder diagram. Doing this change will solve your problem.

Thanks,

Thiago Alves

**Comment by cierzniak** [comment]
Ok, works like a charm, I did not check example program from repository and from OpenPLC Ladder.
